version: "3.8"

services:
  flask-app:
    platform: linux/amd64
    build:
      context: .
      target: development # Use the development stage for building
    ports:
      - "5000:5000"
    environment:
      - "PYTHONPATH=/app"
      - "FLASK_APP=run.py"
      - "ENABLE_QUANTIZATION=true"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 1.8G # t3.small의 90% 사용
        reservations:
          memory: 512M
