version: "3.8"

services:
  flask-app:
    platform: linux/amd64
    build:
      context: .
      target: development # Use the development stage for building
    ports:
      - "5000:5000"
    environment:
      - "PYTHONPATH=/app"
      - "FLASK_APP=run.py"
      - "ENABLE_QUANTIZATION=true"
      - "DATABASE_URL=postgresql://postgres:password@postgres:5432/himeow"
    volumes:
      - .:/app
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 1.8G # t3.small의 90% 사용
        reservations:
          memory: 512M

  postgres:
    image: pgvector/pgvector:pg15
    environment:
      - POSTGRES_DB=himeow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data:
  model_cache: # 모델 캐시 볼륨 추가

networks:
  app-network:
    driver: bridge
