version: "3.8"

services:
  flask-app:
    platform: linux/amd64
    build: .
    ports:
      - "5000:5000"
    environment:
      - "PYTHONPATH=/app"
      - "FLASK_APP=run.py"
      - "FLASK_ENV=development"
      - "MYSQL_HOST=host.docker.internal"
      - "MYSQL_PORT=3306"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=1234"
      - "MYSQL_DB=hi_meow"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
