version: "3.8"

services:
  mysql:
    image: "mysql:8.0"
    environment:
      - "MYSQL_DATABASE=hi_meow"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=1234"
      - "MYSQL_ROOT_PASSWORD=1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root -p1234
      interval: 1s
      timeout: 1s
      retries: 5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
