"""create member and cat tables

Revision ID: 4a3cdcc51307
Revises: 
Create Date: 2025-05-22 19:13:57.170480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3cdcc51307'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_target',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cat',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('breed', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE'), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('last_diagnosis', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('special_notes', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('member_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_rule_description',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_target_id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_rule_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_rule_id'], ['diagnosis_rule.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_target_id'], ['diagnosis_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_level_1',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cat_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('is_normal', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_level_2',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_diagnosis_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_diagnosis_id'], ['diagnosis_level_1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_level_3',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_diagnosis_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_diagnosis_id'], ['diagnosis_level_2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosis_level_3')
    op.drop_table('diagnosis_level_2')
    op.drop_table('diagnosis_level_1')
    op.drop_table('diagnosis_rule_description')
    op.drop_table('cat')
    op.drop_table('members')
    op.drop_table('diagnosis_target')
    op.drop_table('diagnosis_rule')
    # ### end Alembic commands ###
